# Generated by Django 2.0.4 on 2018-04-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beers',
            new_name='Beer',
        ),
    ]
