# Generated by Django 2.0.4 on 2018-04-16 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='beer',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='beers.BeerGenre'),
            preserve_default=False,
        ),
    ]
