# Generated by Django 2.0.4 on 2018-04-23 09:00

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0004_auto_20180416_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
