# Generated by Django 2.0.4 on 2018-04-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0005_beer_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='picture',
            field=models.ImageField(default='media/beersImages/default.png', upload_to='beersImages'),
        ),
    ]
