# Generated by Django 2.0.4 on 2018-04-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0006_auto_20180423_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='picture',
            field=models.ImageField(default='beersImages/default.png', upload_to='beersImages'),
        ),
    ]
